[project]
name = "tomledit"
description = "Format-preserving TOML parser"
readme = "README.md"
authors = [
  { name = "David Hotham" },
]
keywords = ["encoding", "toml"]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = []
dynamic = [
  "license",
  "version",
]

[project.urls]
Repository = "https://github.com/dimbleby/tomledit"

[dependency-groups]
dev = [
  "mypy>=1.19.1",
  "pytest>=8.4.2",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.mypy]
files = "."
strict = true
enable_error_code = [
  "deprecated",
  "explicit-override",
  "ignore-without-code",
  "redundant-expr",
  "truthy-bool",
  "truthy-iterable",
  "unused-awaitable",
]
warn_unreachable = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "C90",               # mccabe
  "COM",               # flake8-commas
  "CPY",               # flake8-copyright
  "D",                 # pydocstyle
  "DOC",               # pydoclint
  "ERA",               # eradicate
  "PD",                # pandas-vet
  "PLR",               # pylint-refactor
  "T20",               # flake8-print
  "ANN401",            # any-type
  "E203",              # whitespace before ':'
  "S101",              # assert-used
]
extend-safe-fixes = [
  "TC",                # flake8-type-checking
]
unfixable = [
  "F841",              # unused-variable
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
