from collections.abc import Iterator
from typing import Any, TypeVar, overload

from typing_extensions import override

_T = TypeVar("_T")

class TomlError(Exception): ...

class Document:
    def __init__(self, data: dict[str, Any] | None = None) -> None: ...
    @staticmethod
    def parse(text: str) -> Document: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: str) -> Item: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, Item]]: ...
    def values(self) -> list[Item]: ...
    @overload
    def get(self, key: str) -> Item | None: ...
    @overload
    def get(self, key: str, default: _T) -> Item | _T: ...
    @overload
    def pop(self, key: str) -> Any: ...
    @overload
    def pop(self, key: str, default: _T) -> Any | _T: ...
    def update(self, other: dict[str, Any]) -> None: ...
    def setdefault(self, key: str, default: Any) -> Item: ...
    def clear(self) -> None: ...
    def fmt(self) -> None: ...
    @property
    def value(self) -> dict[str, Any]: ...

class Item:
    @overload
    def __getitem__(self, key: str | int) -> Item: ...
    @overload
    def __getitem__(self, key: slice) -> list[Item]: ...
    def __setitem__(self, key: str | int | slice, value: Any) -> None: ...
    def __delitem__(self, key: str | int | slice) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __contains__(self, value: Any) -> bool: ...
    def __bool__(self) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @property
    def value(self) -> Any: ...
    # dict-like methods
    def keys(self) -> list[str]: ...
    def values(self) -> list[Item]: ...
    def items(self) -> list[tuple[str, Item]]: ...
    @overload
    def get(self, key: str) -> Item | None: ...
    @overload
    def get(self, key: str, default: _T) -> Item | _T: ...
    @overload
    def pop(self, key: str | int) -> Any: ...
    @overload
    def pop(self, key: str | int, default: _T) -> Any | _T: ...
    @overload
    def pop(self) -> Any: ...
    def update(self, other: dict[str, Any]) -> None: ...
    def setdefault(self, key: str, default: Any) -> Item: ...
    # list-like methods
    def append(self, value: Any) -> None: ...
    def insert(self, index: int, value: Any) -> None: ...
    def remove(self, value: Any) -> None: ...
    def extend(self, values: Any) -> None: ...
    # shared
    def clear(self) -> None: ...
