from collections.abc import (
    ItemsView as _ItemsView,
)
from collections.abc import (
    Iterable,
    Iterator,
    Mapping,
    MutableMapping,
)
from collections.abc import (
    KeysView as _KeysView,
)
from collections.abc import (
    ValuesView as _ValuesView,
)
from typing import Any, TypeVar, overload

from typing_extensions import Self, override

_T = TypeVar("_T")

class KeysView(_KeysView[str]):
    def __reversed__(self) -> Iterator[str]: ...
    @override
    def __and__(self, other: Iterable[Any]) -> set[str]: ...
    @override
    def __or__(self, other: Iterable[_T]) -> set[str | _T]: ...
    @override
    def __sub__(self, other: Iterable[Any]) -> set[str]: ...
    @override
    def __xor__(self, other: Iterable[_T]) -> set[str | _T]: ...
    @override
    def __eq__(self, other: object) -> bool: ...

class ValuesView(_ValuesView[Item]):
    @override
    def __contains__(self, value: object) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...

class ItemsView(_ItemsView[str, Item]):
    @override
    def __contains__(self, item: object) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...

class Document(MutableMapping[str, Any]):
    def __init__(self, data: dict[str, Any] | None = None) -> None: ...
    @staticmethod
    def parse(text: str) -> Document: ...
    @override
    def __contains__(self, key: object) -> bool: ...
    @override
    def __iter__(self) -> Iterator[str]: ...
    @override
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __getitem__(self, key: str) -> Item: ...
    @override
    def __setitem__(self, key: str, value: Any) -> None: ...
    @override
    def __delitem__(self, key: str) -> None: ...
    @override
    def keys(self) -> KeysView: ...
    @override
    def items(self) -> ItemsView: ...
    @override
    def values(self) -> ValuesView: ...
    @overload
    @override
    def get(self, key: str, /) -> Item | None: ...
    @overload
    def get(self, key: str, default: _T, /) -> Item | _T: ...
    @overload
    @override
    def pop(self, key: str, /) -> Any: ...
    @overload
    def pop(self, key: str, default: _T, /) -> Any | _T: ...
    @overload
    @override
    def setdefault(self, key: str, default: None = None, /) -> Item: ...
    @overload
    def setdefault(self, key: str, default: Any, /) -> Item: ...
    @override
    def clear(self) -> None: ...
    def fmt(self) -> None: ...
    def __copy__(self) -> Document: ...
    def __deepcopy__(self, memo: dict[int, Any] | None = None) -> Document: ...
    @property
    def value(self) -> dict[str, Any]: ...

class Item:
    @staticmethod
    def parse(text: str) -> Item: ...
    @overload
    def __getitem__(self, key: str | int) -> Item: ...
    @overload
    def __getitem__(self, key: slice) -> list[Item]: ...
    def __setitem__(self, key: str | int | slice, value: Any) -> None: ...
    def __delitem__(self, key: str | int | slice) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __contains__(self, value: Any) -> bool: ...
    def __bool__(self) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __iadd__(self, values: Iterable[Any]) -> Self: ...
    @property
    def value(self) -> Any: ...
    # comment access
    @property
    def comment(self) -> str | None: ...
    @comment.setter
    def comment(self, value: str | None) -> None: ...
    @property
    def inline_comment(self) -> str | None: ...
    @inline_comment.setter
    def inline_comment(self, value: str | None) -> None: ...
    # dict-like methods
    def keys(self) -> KeysView: ...
    def values(self) -> ValuesView: ...
    def items(self) -> ItemsView: ...
    @overload
    def get(self, key: str, /) -> Item | None: ...
    @overload
    def get(self, key: str, default: _T, /) -> Item | _T: ...
    @overload
    def pop(self, key: str, /) -> Any: ...  # dict-like
    @overload
    def pop(self, key: str, default: _T, /) -> Any | _T: ...  # dict-like
    @overload
    def pop(self, key: int, /) -> Any: ...  # list-like
    @overload
    def pop(self, /) -> Any: ...  # list-like
    @overload
    def update(self, other: Mapping[str, Any], /, **kwargs: Any) -> None: ...
    @overload
    def update(self, other: Iterable[tuple[str, Any]], /, **kwargs: Any) -> None: ...
    @overload
    def update(self, **kwargs: Any) -> None: ...
    @overload
    def setdefault(self, key: str, /) -> Item: ...
    @overload
    def setdefault(self, key: str, default: Any, /) -> Item: ...
    # list-like methods
    def append(self, value: Any, /) -> None: ...
    def insert(self, index: int, value: Any, /) -> None: ...
    def remove(self, value: Any, /) -> None: ...
    def extend(self, values: Iterable[Any], /) -> None: ...
    def count(self, value: Any, /) -> int: ...
    @overload
    def index(self, value: Any, /) -> int: ...
    @overload
    def index(self, value: Any, start: int, /) -> int: ...
    @overload
    def index(self, value: Any, start: int, stop: int, /) -> int: ...
    # shared
    def clear(self) -> None: ...
    def fmt(self) -> None: ...
